language: node_js
before_install:
# See https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-171777646
# Dirty hack for https://github.com/travis-ci/travis-ci/issues/5092
- >
  PATH=`echo $PATH | sed "s/\.\/node_modules\/\.bin//g"`;
  export PATH=$PATH:./node_modules/.bin;
  touch .env;
  if [ $IS_INTEGRATION_TEST ]; then rvm install ruby-2.3.0 --binary && rvm use ruby-2.3.0 && bundle install; else echo "Not an integration test. Skipping Ruby setup"; fi
script: npm run $TEST
addons:
  sauce_connect: true
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    secure: oKBh5J5QbwUVgb8K5mjJ98HIYj5gfThb2PsXS4s6JcXIPDuEEIIRJZ52O338HeVPOdqOImZDfFM51HaZ7ri7QzdD9PaNohiOmgmchKZRbzCGI+iNx+8Aj3+UF7pkd9jnfsc7/Pl9AWyNthmHk85QoNoHtpJt0ljnIiWFBgx3vufPaqWNtH0XljOHd8SDsX9pv83gW5d0JXdffRzurf8AM060ycfJrJ+oYxzCCoWtTeWwzSVQysE+WD7IyfTU4ctdWmlMu1TrZMt6yiP6dmr6fcL4TRJFk5ZqkOjHqCNr5c2e7GTA216rf0VRQN5AdgVoSW0RsRDuJ+cUmZkTBslQz4wJ1MhTi7lFn7zq+1PQLREQ78Du3ub/xaJH3mKcGrv9/P8lBxzqWTl3uydyL7AuQBh8Ej5jdsL/kXH0/cbvEGR8ETrrFyTktAX2rQAlwrq7z5Yem+WH8yx9zAzF3lJ7+Gdl1K+xSNWzTPTqavwSmYrmY5EaZ7r0oo6P2u3lybkSnNmGBM20mSOMBDMqVltF5FWT3SWadOnk0tlio67dx0JSh9BzjNsa3A554Ut49+JYhOznJrstf4kqf+GPP5vdfKjqko7Lu7ygVx40zBzaCeyX5YPT5wQqD0JcyZrn1EFzfuthk8+u00OzQErR2p025KQvsxl2uCCIXp5kI7hrxmI=
env:
  matrix:
  - TEST="lint"
  - TEST="test:unit"
  - TEST="test:integration" PLATFORM="desktop" IS_INTEGRATION_TEST=true
  # iOS tests on Travis are flaky. Run these manually before merging something in
  # - TEST="test:integration" PLATFORM="ios" IS_INTEGRATION_TEST=true
  global:
  - secure: SvjZyrdqFJBWCgduVObookkrTLIer/OF4yILB5uy5DuzDT52vmUGLKWj1Zjevy6PKdoZ3QPdrbrEn8tIRuiiTCbBTi9X3X8cQjVHN1Jxq1w/TIUiCxg1Wt+M+FnS2EamLMo2BFEsCM5qXrLwUd23uLXxMRJKDikBvaq1Lgib+S3CDhROORgEtnZeXXd328NiUNriDadhnC7kTACZ16Urt9ZrTJrXwQLujNJlO/zVxB0dBTV8Hzjp/Qce/D3XFg943xeHj7UuffF9ntcJqGEImY226VVWwk3D78j9zpfOXCIBJD/h/uls77eZzSi/9o2voVqfWHGuuKoRfVC8772kuWoe95Fm8ntFUbEWutDnfhs7aMqSW4rYMbFUSMqf6qBGWse07clk6zx0cZpsC1vscf3QSDQu/joj8ohX6+1Qn4gd+1/Rp3WjLBdWUcTfcODLspahwXZ5xnkzU04m46eO23E++U6WYD22xJnHZVsWHM+aGcDRQYFg07mnzOQwSUs66qXpMLCiL4vFiZ4tTehzTD3iMNF+3cr8WDlgFUH9rNBJjzYJeCOycdxwQg9f7orh/Iwm8TdcWQAxpXaWdfa6KidY/4fDi7gCCoxePjuDHnDXt8e+xlMYIM3fy+xfHb7GWCyGnHdQRxLEPFSTPnTDyWVcg7CSbGl9YmqMRa7SMus=
  - secure: u5obPww8nFh3zcov6B9jBj/7LldTT+jOWOUQv/MxE65G6dFWhyJIiNSG/f7HtYr/ziY77B5a+SIoYd097G5lqrtMj128cCGvamdXye0d3YzrbtVGiN7wS3cXPlRPORcaPhQkRl4tQPsElj742f9FRWXsXLdGDzmpPAJDO0lBk9SZuRfdNvw9nTvoHHZgQxu2/lHaMie6v2B3iXSgmgtTN5r6qXXlDoCxZlCB+4cVY2SVNAwXoNk3DDBYsWdOAzVWaOO28l1NaH5CAoKHpz9x1YjjOdHBER5mG2EogQ5Mo4/CAsO9VuEL5Mp0sfhEG7tPXdM0GktFxiRSGfYGIbaMkRUA2npwhj0cWBPdPGaMTQHZI/anr8VHaxUlEP84gXw8VvavttBpaDS/Wdz5dIy5cbqB2q3xhE0VGaR2fG39O/MA+Oq89ZUhThgS8YqltMOKe5AYM3nIeQje61NUpb7FC5q6VLuIKVfSyak2r+TFSVdI27DwU8/QrTIItl1yYJh9eASMX2VIudUahxz0twK7jXuLc9zYtOHgH4bty997G1Z/sr7vu6upyz6081p2tdPDWXzSVIU0HfLj8wRCFnvI8rkKOWfJUGg8ikKJcWoJON3Q59LiuqnEafDiehUnnuueHw5FRi8gcmw82PvFxtoQLzIxfPPNy8k7P2ghsormLjU=
